[build]
  base = "/"
  publish = "out" # or ".next" if you're using `next build` without `next export`
  command = "npm run build"

[build.environment]
  NODE_ENV = "production"

[build.caching]
  # Cache node_modules
  directory = "node_modules"